name: Generate Release Notes

on:
  release:
    types: [published]

jobs:
  create-confluence-page:
    runs-on: ubuntu-latest    
    steps:
      - name: Publish to Confluence Action
        uses: Gershon-A/publish-release-to-confluence@v1.0.4
        with:
          confluence_email: ${{ vars.CONFLUENCE_EMAIL }}
          confluence_api_token: ${{ secrets.CONFLUENCE_API_TOKEN }}
          spaceId: '131077'
          status: 'current'
          title: "Release: ${{ github.ref_name }}"
          parentId: '327738'
          ConfluenceBaseUrl: 'https://eyalty.atlassian.net'
          repoOwner: ${{ github.repository_owner }}
          repoName: ${{ github.event.repository.name }}
          tag: ${{ github.ref_name }}
          appName: ${{ github.event.repository.name }}